Изменена логика отображения нового квадрата для фото
ilya-konanykhin/neofiles pull request #19
Opened 2018-10-18 20:12 UTC by Arlantir

2019-04-18 11:02 UTC, ilya-konanykhin commented on app/views/neofiles/admin/_file_compact.html.haml
> +  - if append_create and file
`and` -> `&&`

2019-04-18 11:02 UTC, ilya-konanykhin commented on lib/neofiles/engine.rb
> +    config.neofiles.album_append_create_side = :right # picture when added is displayed on the right
Перечисление всех опций есть в README вроде, туда тоже надо добавить?

2019-04-18 21:29 UTC, Arlantir commented on lib/neofiles/engine.rb
> +    config.neofiles.album_append_create_side = :right # picture when added is displayed on the right
Добавил

2019-04-18 21:29 UTC, Arlantir commented on app/views/neofiles/admin/_file_compact.html.haml
> +  - if append_create and file
Поправил, глаз алмаз

2019-04-22 10:05 UTC, ilya-konanykhin requested changes
вытяни свежак из master, пожалуйста, там есть важные правки

2019-05-08 06:32 UTC, ilya-konanykhin approved these changes

2019-05-08 06:32 UTC, merged